name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        continue-on-error: true
        id: lint_first_try
        with:
          args: --print-issued-lines --config .golangci.yml -v

      - name: Lint Retry 1
        if: steps.lint_first_try.outcome == 'failure'
        uses: golangci/golangci-lint-action@v4
        continue-on-error: true
        id: lint_retry_1
        with:
          args: --print-issued-lines --config .golangci.yml -v

      - name: Lint Retry 2
        if: steps.lint_retry_1.outcome == 'failure'
        uses: golangci/golangci-lint-action@v4
        id: lint_retry_2
        with:
          args: --print-issued-lines --config .golangci.yml -v